name: Build and Push image to registry

on:
  push:
    tags:
    - v*.*.*
    branches:
      - dev 
      - stage
    paths:
      - '**.*'
 
  release:

    
jobs:
# Workflow defines what trigger an action and uses action that is suitable for the process
  trigger-build:
    if: ${{ github.event_name == 'push'  }}
    uses: wgall/cloudrun_node_cicd/.github/workflows/main.yml@dev
    secrets: 
      sakey: ${{ secrets.SA_CREDENTIALS }}
      token: ${{ secrets.CLOUDRUN_GIT_TOKEN }}
  production: 
    if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
    uses: wgall/cloudrun_node_cicd/.github/workflows/production.yml@dev
    secrets: inherit
